In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.5


In [4]:
a=np.array([1,2,3,45,5])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(5,)

In [7]:
a.ndim

1

# list of array

In [ ]:
a=([1,2,3,45,5])

In [8]:
import numpy as np

In [9]:
type(a)

numpy.ndarray

In [10]:
b=np.array(a)

In [11]:
type(a)

numpy.ndarray

In [12]:
a1=([10,11,12,13,14])

In [13]:
type(a)

numpy.ndarray

In [14]:
typelist=list(a)

In [15]:
type(typelist)

list

In [16]:
a1 = ([10,11,12,13,14,15,16])

In [17]:
res=list(a1)

In [18]:
type(a1)

list

In [19]:
np.array(a1)

array([10, 11, 12, 13, 14, 15, 16])

In [21]:
ress=type(a1)

In [23]:
type(a1)

list

In [24]:
a5=([2,3,4,5])

In [25]:
type(a5)

list

In [26]:
ans=np.array(a5)

In [27]:
type(ans)

numpy.ndarray

In [28]:
ans1=list(ans)

In [29]:
type(ans1)

list

In [30]:
seq_a=[1,2,3]
seq_b=[5,6,7]
seq_c=[8,9,10]

In [31]:
mod=np.array([seq_a,seq_b,seq_c])

In [32]:
mod.ndim

2

In [33]:
mod.shape

(3, 3)

# 05 AUGUST 2020A


# RESHAPING

In [21]:
import numpy as np

In [3]:
newarray=np.array([[1,2,3],[2,3,4]])

In [4]:
newarray.shape

(2, 3)

In [5]:
newarray.reshape(1,6)

array([[1, 2, 3, 2, 3, 4]])

In [6]:
newarray.reshape(3,2)

array([[1, 2],
       [3, 2],
       [3, 4]])

In [7]:
newarray.ndim

2

In [8]:
newarray.reshape(2,3)

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
newarray.size

6

In [11]:
a=([1,2,3,4,5,6])

In [12]:
import sys

In [14]:
sys.getsizeof(a)

104

In [15]:
type(a)

list

In [16]:
seq_a=[1,2,3]
seq_b=[4,5,6]
seq_c=[7,8,9]
seq_d=[10,1,12]

In [17]:
arrayabcd=np.array([seq_a,seq_b,seq_c,seq_d])

In [18]:
arrayabcd.size

12

In [19]:
arrayabcd.itemsize

8

# reshaping

In [27]:
arr1d

NameError: name 'arr1d' is not defined